spring.application.name=32-IDENTITY-PK-Generation-MYSQL

# ===============================
# PostgreSQL Database Configuration
# ===============================

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/sb01db

spring.datasource.username=root

spring.datasource.password=root@123


# ===============================
# JPA / Hibernate Configuration
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create

