#Admin Server Configuration
admin.url=https://admin.tca.com
admin.port=7070
admin.user=admin
admin.password=root@123


# Email Server Configuration
smpt.host=smtp.gmail.com
smpt.port=9090
to.address=akshay@gmail.com
from.address=tca@gmail.com